1-Create a (5, 5) array of random integers between 0 and 100. Replace every value greater than 50 with 0, using boolean masking (no loops).

In [12]:
import numpy as np
rng=np.random.default_rng(seed=42).integers(low=0,high=100,size=(5,5))
rng[rng>50]=0
print(rng)


[[ 8  0  0 43 43]
 [ 0  8  0 20  9]
 [ 0  0  0  0  0]
 [ 0  0 12  0 45]
 [50 37 18  0  0]]


2-Given a (10, 3) array representing 10 samples with 3 features, compute the min-max normalized version (each feature scaled to [0, 1]) using only vectorized operations and broadcasting.

In [31]:
new_array=np.random.normal(loc=0,scale=1,size=(10,3))
print(new_array)
print("max is column",new_array.max(axis=0))
print("min is column",new_array.min(axis=0))
print("max is row",new_array.max(axis=1))
print("max is row",new_array.max(axis=1))       
                                 

[[ 0.40358379  0.33101689 -0.64144572]
 [-1.00940984  0.2008753  -1.11897169]
 [-1.00683202 -1.278824   -0.37622046]
 [ 0.13217289 -1.58970532  1.44922159]
 [-0.3213053  -0.15772146  0.3773197 ]
 [ 1.29426617 -1.14094635  1.60917706]
 [ 0.00276261 -0.46514622  0.32050973]
 [-0.45476092  0.49000943 -1.22355151]
 [ 1.96433298 -2.12108596  1.62448184]
 [ 1.14889147  0.57065814 -0.80346634]]
max is column [1.96433298 0.57065814 1.62448184]
min is column [-1.00940984 -2.12108596 -1.22355151]
max is row [ 0.40358379  0.2008753  -0.37622046  1.44922159  0.3773197   1.60917706
  0.32050973  0.49000943  1.96433298  1.14889147]
max is row [ 0.40358379  0.2008753  -0.37622046  1.44922159  0.3773197   1.60917706
  0.32050973  0.49000943  1.96433298  1.14889147]


3-Write a vectorized version of the Euclidean distance between two (n,) vectors, and confirm it matches np.linalg.norm(a - b).

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.sum((a-b)**2)
d=np.sqrt(c)
e=np.linalg.norm(a - b)
if e==d:
    print("d")
else:
    print("False")                                                 

true


4-Time a vectorized computation of x**2 + 2*x + 1 for 1 million elements against the equivalent Python for loop, and report the speedup yourself.

In [ ]:
#Developing......