1-Create a (5, 5) array of random integers between 0 and 100. Replace every value greater than 50 with 0, using boolean masking (no loops).

In [1]:
import numpy as np
rng=np.random.default_rng(seed=42).integers(low=0,high=100,size=(5,5))
rng[rng>50]=0
print(rng)


[[ 8  0  0 43 43]
 [ 0  8  0 20  9]
 [ 0  0  0  0  0]
 [ 0  0 12  0 45]
 [50 37 18  0  0]]


2-Given a (10, 3) array representing 10 samples with 3 features, compute the min-max normalized version (each feature scaled to [0, 1]) using only vectorized operations and broadcasting.

In [2]:
new_array=np.random.normal(loc=0,scale=1,size=(10,3))
print(new_array)
print("max is column",new_array.max(axis=0))
print("min is column",new_array.min(axis=0))
print("max is row",new_array.max(axis=1))
print("max is row",new_array.max(axis=1))       
                                 

[[-1.52828373 -2.9912259  -0.17593222]
 [-1.19178816  0.25987213 -0.27989658]
 [ 1.29882491 -0.88225723 -0.52400303]
 [-1.11503153  0.45569145  1.01812869]
 [-0.44522356  0.07439498  0.98134591]
 [-2.3468948   0.73664782  1.03558102]
 [ 1.48355481  0.328147    1.18462025]
 [ 1.35090251  0.99690376  1.49908395]
 [ 1.07820503  0.5677565  -0.22290918]
 [-0.09820978 -0.21393023  1.79542922]]
max is column [1.48355481 0.99690376 1.79542922]
min is column [-2.3468948  -2.9912259  -0.52400303]
max is row [-0.17593222  0.25987213  1.29882491  1.01812869  0.98134591  1.03558102
  1.48355481  1.49908395  1.07820503  1.79542922]
max is row [-0.17593222  0.25987213  1.29882491  1.01812869  0.98134591  1.03558102
  1.48355481  1.49908395  1.07820503  1.79542922]


3-Write a vectorized version of the Euclidean distance between two (n,) vectors, and confirm it matches np.linalg.norm(a - b).

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.sum((a-b)**2)
d=np.sqrt(c)
e=np.linalg.norm(a - b)
if e==d:
    print("d")
else:
    print("False")                                                 

d


4-Time a vectorized computation of x**2 + 2*x + 1 for 1 million elements against the equivalent Python for loop, and report the speedup yourself.

In [4]:
import time

x = np.random.rand(1_000_000)


start = time.perf_counter()

y_vector = x**2 + 2*x + 1

vector_time = time.perf_counter() - start

start = time.perf_counter()

y_loop = np.empty_like(x)

for i in range(len(x)):
    y_loop[i] = x[i]**2 + 2*x[i] + 1

loop_time = time.perf_counter() - start

speedup = loop_time / vector_time

print(f"Vectorized time: {vector_time:.6f} seconds")
print(f"For loop time : {loop_time:.6f} seconds")
print(f"Speedup: {speedup:.2f}x")

Vectorized time: 0.013825 seconds
For loop time : 0.947735 seconds
Speedup: 68.55x
